<a href="https://colab.research.google.com/github/M4rcoM04/DSBootcamp/blob/main/01_intro_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello Collab')

Hello Collab


In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.23.5'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim
# to sprawdza wymiar

1

In [ ]:
x.shape
# to pokazuje kształt
# najczęściej wykorzystywany

(2,)

In [ ]:
x.size
# pokazuje liczbę elementów w tablicy

2

In [ ]:
x.dtype
# typ danych
# najczęsciej wykorzystywany

dtype('int64')

In [ ]:
x = np.array([1.4, 4.5, 2.8])
print(x)

[1.4 4.5 2.8]


In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
y = np.array([[1, 2], [3, 4]])
y

array([[1, 2],
       [3, 4]])

In [ ]:
y.ndim

2

In [ ]:
y.shape

(2, 2)

In [ ]:
y.dtype

dtype('int64')

In [ ]:
y = np.array([[1, 2, 3], [2, 3, 4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [ ]:
x.shape

(3,)

In [ ]:
y = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
print(y)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


3D Array

In [ ]:
# 3D pozwala przekazywać takie informancje jak np. obraz
z = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

      [[4, 1, 3],
       [4, 2, 1]]]
)
z

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
z.ndim

3

In [ ]:
z = np.array([[[4, 3, 1], [3, 1, 2]], [[4, 1, 3], [4, 2, 1]]])

In [ ]:
z. shape

(2, 2, 3)

Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype


dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.3])
A.dtype


dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='float')
A.dtype


dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype


dtype('complex128')

In [ ]:

A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

array([1, 2, 3])

In [ ]:
A

array([1, 2, 3])

Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10))
# domyśle typ naszych liczb to float

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape = (3, 3), fill_value=4, dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start = 5, stop = 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start = 10, stop = 100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start = 100, stop = 10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start = 0, stop = 1, num = 11)
#num mówi o liczbe elementów które chcemy wygenerować. które są równomiernie rozłożone


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#żeby zmienić rozmiar danych A, możemy użyć A.reshape()
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(3, -1)
# to oznacza, że 3 wiersze i Python niech dobierze odpowiednią ilość kolumn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [ ]:
# dodawanie jest element po elemencie
A + B

array([6, 0, 7, 4])

In [ ]:
# jednak preferowana metoda to jest przez funkcję add
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
A - B
# albo
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
A * B
# albo
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
# przy dzieleniu zwraca nam liczby typu float mimo, że na początku były int
A / B
# albo
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A * 2

array([6, 2, 8, 4])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

In [ ]:
# mnożenie macierzowe
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y

array([[6, 0],
       [2, 0]])

In [ ]:
# mnożenie macierzowe
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
# trzeba pamiętać, że z macierzami nie ma tak, że X * Y to to samo co Y * X
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [ ]:
X @ Y
#to samo co X.dot(Y)

array([[  3,   6],
       [-12,   0]])

Generowanie  liczb pseudolosowych


In [ ]:
np.random.seed(0)
# ziarno losowe pozwala zawsze uzyskać ten sam wynik losowania xD

In [ ]:
# randn - losowy układ normlany
np.random.randn(10)
# to co w nawiasie to mówi nam ile ma być wylosowanych liczb losowych

array([ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433,
        1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982])

In [ ]:
np.random.randn(10, 4)
# 10 wiersze, 4 kolumny


array([[ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785],
       [-0.21274028, -0.89546656,  0.3869025 , -0.51080514],
       [-1.18063218, -0.02818223,  0.42833187,  0.06651722],
       [ 0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

In [ ]:
np.random.rand()
# przedział jednostajny na przedziale (przedział 0, 1, prawostronnie otwarty)

0.41426299451466997

In [ ]:
np.random.rand(10)

array([0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805,
       0.09394051, 0.5759465 , 0.9292962 , 0.31856895, 0.66741038])

In [ ]:
np.random.rand(10, 2)

array([[0.13179786, 0.7163272 ],
       [0.28940609, 0.18319136],
       [0.58651293, 0.02010755],
       [0.82894003, 0.00469548],
       [0.67781654, 0.27000797],
       [0.73519402, 0.96218855],
       [0.24875314, 0.57615733],
       [0.59204193, 0.57225191],
       [0.22308163, 0.95274901],
       [0.44712538, 0.84640867]])

In [ ]:
np.random.randint(10)
# losowa liczba całkowita od 0 do tej którą podamy

6

In [ ]:
#size mówi o tym ile tych danych mamy wygenerować
np.random.randint(low = 10, high = 100, size = 10)

array([23, 81, 66, 34, 89, 51, 28, 50, 64, 89])

In [ ]:
np.random.choice([4, 2, 1, 9])
# funkcja choice wybierze nam randomowo obiekt z listy którą podamy

2

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'java'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
# tutaj mamy od razu zmianę naszych danych, nie trzeba tego dodatkowo przypisać
# do innego albo tego samego obiektu

In [ ]:
data

array([1, 0, 6, 5, 4, 7, 9, 2, 3, 8])

Podstawowe funkcje numpy

In [ ]:
np.exp(1)
# zwraca nam eksponent czyli e^x w tym wypadku e^1

2.718281828459045

In [ ]:
# pieriastek
np.sqrt(9)

3.0

In [ ]:
np.all([2, 3, 1])
# funkcja all przechodzi po kazdym obiekcie i patrzy czy zwraca True czy False
# jeśli każda zwróci prawdę to w wyniku zwróci nam True

True

In [ ]:
np.all([2, 0, 1])

False

In [ ]:
# funkcja any sprawdza czy jakikolwiek obiekt jest prawdą
np.any([2, 0, 1])

True

In [ ]:
A = np.random.randn(5)
A

array([-0.35955316,  0.61407937,  0.92220667,  0.37642553, -1.09940079])

In [ ]:
# zwrócenie indeksu wartości największej
np.argmax(A)

2

In [ ]:
A[np.argmax(A)]


0.9222066715665268

In [ ]:
# zwrócenie indeksu wartości najmniejszej
np.argmin(A)

4

In [ ]:
A[np.argmin(A)]

-1.0994007905841945

In [ ]:
np.argsort(A)
# zwróci listę z indeksami wartości od najmniejszej

array([4, 0, 3, 1, 2])

In [ ]:
# wyrzuci numer który jest największy, najmniejszy
np.max(A)
np.min(A)

-1.0994007905841945

In [ ]:
#średnia
np.mean(A)

0.09075152418870017

In [ ]:
#mediana
np.median(A)

0.37642553115562943

In [ ]:
# odchylenie standardowe
np.std(A)

0.7302104049204363

Wycinanie i ideksowanie

In [2]:
import numpy as np

In [4]:
A = np.arange(20)
# wycinanie
# A[idx], A[start:stop], A[:stop], A[start:]

In [ ]:
A[2]
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
# wycinanie dówch konretych ideksów
# A[[idx, idx]]
A[[0,3]]

array([0, 3])

In [5]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# wycięcie wiersza
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
# wycięcie kolumny
A[:, 1]

array([ 1,  6, 11, 16])

In [ ]:
# żeby wyciąć konkretny element to A[wiersz, kolumna]
# czyli 7 jest w 2 wierszu i 3 kolumnie
A[1, 2]

7

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [10]:
# A.flat wypłaszcza tablice i można iterować element po elemencie
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [11]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
A.shape

(4, 5)

In [14]:
#zmiana rozmiaru talicy
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
# wypłaszczanie dany A.ravel()
A.ravel()
# i potem A.reshape()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
#transponowanie tablicy czyli zamiana wierszy na kolumny  i kolumny na wiersze
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [18]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [19]:
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [20]:
#stowrzenie maski logicznej
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
# używając maski logicznej jak wycinać
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [22]:
# zamiast pisać A > - 5 and A < 5 bo numpay tego nie ogatrnie,
# trzeba użyć funkcji bitwise_and()
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [24]:
np.bitwise_or(A > -5, A < 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])