<a href="https://colab.research.google.com/github/M4rcoM04/DSBootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Norma wektora, długość wektora w R^2**


In [1]:
import numpy as np

v = [v1, v2]  
||v|| = (v1^2 + v2^2)^(1/2)

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
# norma wektor np.linalg.norm()
np.linalg.norm(v1)

4.123105625617661

**Norma euklidesowa w R^n**

||v|| = (v1^2 + v2^2+....+ vn^2)^(1/2)

In [ ]:
v2 = np.array([-10, 10, 13])

In [ ]:
np.linalg.norm(v2)

19.209372712298546

**Odległość dwóch punktów na płaszczyźnie**

d=√((x2 - x1)²+(y2 - y1)²)

In [ ]:
p = np.array([3, 0])
q = np.array([0,4])

np.linalg.norm(p - q)

5.0

**Odległość dwóch punktów na przestrzeni R^n**

d(x, y) = √((y1 - x1)²+ (y2 - x2)² +...+ (yn - xn)²)

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0,4, 2])

np.linalg.norm(p - q)

5.0990195135927845

**Mnożenie macierzy**

In [ ]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [ ]:
# mnożenie macierzy mp.dot
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X)
print(Y)

[[ 2 -1  3]
 [ 3  1  0]]
[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

**Wyznacznik macierzy**

In [2]:
#obliczanie wyznacznika macierzy
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

In [3]:
# jeśli chcemy zaokrąglenie to używamy round()
round(np.linalg.det(A))

10

**Ślad macierzy**

In [5]:
np.trace(A)

5

**Macierz jednostkowa**

In [6]:
# generowanie macierzy jednostkowej
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

**Macierz odwrtona**

In [8]:
# tylko macierze kwadratowe można obracać
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

**Macierz transponowana**

In [9]:
A

array([[ 2,  4],
       [-1,  3]])

In [11]:
np.transpose(A)
#albo
A.T

array([[ 2, -1],
       [ 4,  3]])

**Rozwiązywanie układów równań**

In [12]:
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [14]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [16]:
# macierz odwrotna do macierzy A
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])