<a href="https://colab.research.google.com/github/M4rcoM04/DSBootcamp/blob/main/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:


price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


**sum()**

In [ ]:
#suma wszystkich elementów w tablicy
price.sum()

4650.1

In [ ]:
# suma w każdej kolumnie, axis = 0
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [ ]:
#suma w każdym wierszu, axis = 1
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [ ]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

**min()**

In [ ]:
np.min(price)

11.7

**max()**

In [ ]:
np.max(price)

2000.0

**median()**

In [ ]:
np.median(price)

12.6

**mean()**

In [ ]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

**std()**
Odchylenie standardowe

In [ ]:
np.std(price)

622.3781502877133

**var()**
wariancja

In [ ]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])